# Bootloader

# Driver
CONFIG_SPI=y
CONFIG_FLASH=y

# Logging
CONFIG_LOG=y

CONFIG_SHELL=y
CONFIG_FLASH_SHELL=y

# MCU MGR
CONFIG_NET_BUF=y
CONFIG_ZCBOR=y
CONFIG_CRC=y
CONFIG_MCUMGR=y

# Support for echo command
CONFIG_MCUMGR_GRP_OS=y 
CONFIG_MCUMGR_GRP_OS_ECHO=y
CONFIG_MCUMGR_GRP_SHELL=y

# MCUmgr with serial
CONFIG_BASE64=y
CONFIG_CRC=y
CONFIG_MCUMGR_TRANSPORT_UART=y
CONFIG_CONSOLE=y

# MCUmgr with shell
# CONFIG_BASE64=y
# CONFIG_CRC=y
# CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_DUMMY=y
# CONFIG_SHELL_BACKEND_SERIAL=y
# CONFIG_MCUMGR_TRANSPORT_SHELL=y

# mcumgr-cli application doesn't accepts log in the channel it uses
# CONFIG_SHELL_LOG_BACKEND=n
